# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    # branches: [ "main", "test" ]
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
    # branches: [ "main", "test" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install app
      run: npm install
    
    - name: Build app
      run: npm run build --if-present
      
    - name: Run unit tests
      run: npm test
      
    - name: Run lint
      run: npx eslint ./src
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Test Environment
        run: railway up
        if: github.ref == 'refs/heads/test'
        env:
          RAILWAY_TOKEN: ${{ secrets.TEST_ACTIONS_TOKEN }}

      - name: Deploy to Production Environment
        run: railway up
        if: github.ref == 'refs/heads/main'
        env:
          RAILWAY_TOKEN: ${{ secrets.TEST_ACTIONS_TOKEN }}
